kind: pipeline
type: docker
name: portdb.yaleman.org

steps:
- name: Update s3 contents
  image: jojomi/hugo:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    CLOUDFLARE_API_KEY:
      from_secret: CLOUDFLARE_API_KEY
    CLOUDFLARE_EMAIL:
      from_secret: CLOUDFLARE_EMAIL
  commands:
  - hugo
  - hugo deploy --dryRun
#- name: terraform apply
#  image: hashicorp/terraform:light
#  environment:
#    AWS_ACCESS_KEY_ID:
#      from_secret: AWS_ACCESS_KEY_ID
#    AWS_SECRET_ACCESS_KEY:
#      from_secret: AWS_SECRET_ACCESS_KEY
#    CLOUDFLARE_API_KEY:
#      from_secret: CLOUDFLARE_API_KEY
#    CLOUDFLARE_EMAIL:
#      from_secret: CLOUDFLARE_EMAIL
#  commands:
  # - mkdir ~/.aws/
  # - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" > ~/.aws/credentials
  # - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  # - echo "region = us-east-1" >> ~/.aws/credentials
  # - cat ~/.aws/credentials
  # - echo "$TERRAFORM_CONFIG" | base64 -d > _config.tf
  #- terraform init
 # - terraform apply -auto-approve
