base_url = "https://portdb.yaleman.org"
title = "portDB"
description = "A practical reference for TCP and UDP port numbers"
default_language = "en"
output_dir = "output"
compile_sass = false
build_search_index = false
minify_html = true

[markdown]
smart_punctuation = true

[extra]
repository_url = "https://github.com/yaleman/portdb.yaleman.org"
