[tool.poetry]
name = "portdb_yaleman_org"
version = "0.0.1"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pelican = {extras = ["markdown"], version = "^4.7.2"}
ghp-import = "^2.1.0"
requests = "^2.28.0"

[tool.poetry.dev-dependencies]
pylint = "^2.14.2"
pytest = "^7.1.2"
black = "^22.3.0"
mypy = "^0.961"
types-requests = "^2.27.30"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
