[tool.poetry]
name = "portdb_yaleman_org"
version = "0.0.1"
description = ""
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
ghp-import = "^2.1.0"
requests = "^2.30.0"
invoke = "^2.1.1"
livereload = "^2.6.3"

[tool.poetry.dependencies.pelican]
extras = [
    "markdown",
]
version = "^4.8.0"

[tool.poetry.dev-dependencies]
pylint = "^2.17.4"
pytest = "^7.3.1"
black = "^23.3.0"
mypy = "^1.3"
types-requests = "^2.30.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.269"
mypy = "^1.3.0"
black = "^23.3.0"
types-invoke = "^2.0.0.7"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "portdb_yaleman_org"
description = ""
license = "MIT"
version = "0.0.1"
authors = [
    { name = "James Hodgkinson", email = "james@terminaloutcomes.com" },
]

[tool.ruff]
line-length = 200