[tool.poetry]
name = "portdb_yaleman_org"
version = "0.0.1"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pelican = {extras = ["markdown"], version = "^4.8.0"}
ghp-import = "^2.1.0"
requests = "^2.28.2"

[tool.poetry.dev-dependencies]
pylint = "^2.17.2"
pytest = "^7.2.2"
black = "^23.3.0"
mypy = "^1.1"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
